FROM mcr.microsoft.com/vscode/devcontainers/base

#RUN curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
RUN curl -L https://releases.jetpack.io/devbox -o /usr/bin/devbox && chmod +x /usr/bin/devbox
#RUN echo 'eval "$(direnv hook bash)"' >> ~/.bashrc